name: Publish to AUR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version String'     
        required: true
      pkgrel:
        description: pkgrel
        required: true
        default: "1"
      sha256sum:
        description: sha256 Checksum of .tar.gz file
        required: true

jobs:
  aur-publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Replace VERSION_STRING in PKGBUILD file with parameter
        run: sed -i 's/VERSION_STRING/${{ github.event.inputs.version }}/g' PKGBUILD
        
      - name: Replace PKGREL in PKGBUILD file with parameter
        run: sed -i 's/PKGREL/${{ github.event.inputs.pkgrel }}/g' PKGBUILD  
        
      - name: Replace 256SUM in PKGBUILD file with parameter
        run: sed -i 's/256SUM/${{ github.event.inputs.sha256sum }}/g' PKGBUILD  

      - name: Output PKGBUILD for debugging purposes
        run: cat PKGBUILD

      - name: Publish AUR package with modified PKGBUILD
        uses: KSXGitHub/github-actions-deploy-aur@v2.2.5
        with:
          pkgname: memeassembly
          pkgbuild: ./PKGBUILD
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          ssh_keyscan_types: rsa,dsa,ecdsa,ed25519
